### ISSUE TITLE
Group 4 task: create socket, accept connection, call parse_message, process_operation and send_reply

### ISSUE THREAD

**Issue by zhangwei1984** [gwAdvNet2015/gw-kv-store#14]
We use thread pool. There is a task list. The procedure is the following:
1) Create the defined threads. 
2) When a new connection comes, create a task and put to the tail of a task list. 
3) Each thread will get a task from the task list and process it. 
4) Use mutex and conditional variable to protect and synchronize the shared task list. 

Need other groups to provide the parse_message and process_operation functions for us. 

void parse_message(char *message, int len, struct operation *operation);
void process_operation(struct operation *operation, char *message, int *len);

**Comment by twood02** [comment]
In the next class you will have to do some tests to verify that your thread pool works correctly.

Since you are providing a multi-threaded server, you will have to coordinate with the other groups to ensure that they provide a `process_operation` function that is thread safe (or clearly specify what workloads you can handle).

**Comment by twood02** [comment]
this will all be solved by #28 once that gets merged.

**Comment by hooohu** [comment]
Hello, my group will keep modifying the pull request of thread pool server. I hope it is compilable and good at basic tests. We will merge it ASAP.

**Comment by hooohu** [comment]
New Pull Request #39

**Comment by twood02** [comment]
@zhangwei1984  @hantasm @wenhuizhang  - please update this Issue or close it and create a new one listing exactly what is remaining and who will do what

**Comment by wenhuizhang** [comment]
Hello, my group will work with other groups, waiting for final decisions of API for parse_message, process_operation function. And get it updated.

**Comment by zhangwei1984** [comment]
We have already tested our multi-threads with non-memcached  protocol client. 
What we need:
1) From server logic team: parse_message and process_operation. If your group make these two operations in one function (the current version), that is fine to us. Your group should provide  us the interfaces for these operations, give the operation result and we will send it to the client.  Merge the code to our server  Infrastructure code. 

2) From client team: To test the whole framework work, we need  to use your group code send the real memcached requests to the server and send the response back  to the client.

**Comment by zhangwei1984** [comment]
We do not use gwkv_marshal_server in marshal lib. It seems it is not what we need. 
In gwkv_demarshal_server function, the standard set protocol  is "set key 0 0 value_length\r\nvalue\r\n". After value_length, there is no space ' '. In our marshal lib, the command should be "set key 0 0 value_length \r\nvalue\r\n". It seems that  we can not use other memcached benchmarks to test it.

**Comment by amygara** [comment]
Server finished and merged to master, see PR #65
