### ISSUE TITLE
Fix ht-wrapper Test

### ISSUE THREAD

**Issue by phil-lopreiato** [gwAdvNet2015/gw-kv-store#32]
It breaks.

in `server/test` you should be able to run `make` and have the compiled file run without error

**Comment by phil-lopreiato** [comment]
@smonaghan I made everything pass in #33 (which will be merged soon) . Can you instead make the tests a little more complete?

**Comment by twood02** [comment]
@SMonaghan @phil-lopreiato  - please update this Issue or close it and create a new one listing exactly what is remaining and who will do what

**Comment by phil-lopreiato** [comment]
Fixed in #36

**Comment by phil-lopreiato** [comment]
Nothing more needs to be done here
