### ISSUE TITLE
Travis CI Unit Tests

### ISSUE THREAD

**Issue by phil-lopreiato** [gwAdvNet2015/gw-kv-store#33]
Do it

Enabled automated continuous integration unit testing through http://travis-ci.org

See [an example](https://travis-ci.org/phil-lopreiato/data-structures)

**Comment by phil-lopreiato** [comment]
@twood02 You need to do the following (see [getting started page](http://docs.travis-ci.com/user/getting-started/#Step-one%3A-Sign-in)):
- Go to https://travis-ci.org/
- Hit 'Sign in with GitHub' (top right)
- On the left column, hit the + icon to add a new repository
- Flip the switch for this one (in the settings, make sure you've enabled 'Only build if .travis.yml is present')

**Comment by twood02** [comment]
I think this is complete.  Let me know if you need anything else from me.

---

Timothy Wood, Ph. D.
Assistant Professor
Department of Computer Science
The George Washington University
http://www.seas.gwu.edu/~timwood

**Comment by twood02** [comment]
can we have travis do things like check style guide compliance?

**Comment by phil-lopreiato** [comment]
Do you know of any command line programs that can do that? Travis just runs
a command on the repo in a docker container, so anything you can run, it
can do.

Can GNU indent do enforcement?

**Comment by phil-lopreiato** [comment]
Also, another problem is that @gparmer's style guide is weird and doesn't follow any existing major style completely (it has some features `intent` can't do, like the return type of a function on its own line).

If somebody has the time, they can modify Google's `cpplint` ([link](https://google-styleguide.googlecode.com/svn/trunk/cpplint/cpplint.py)) to do it. It'll work perfectly, as long as we follow Google's coding style...
