### ISSUE TITLE
Handler

### ISSUE THREAD

**Issue by nks5295** [gwAdvNet2015/gw-kv-store#35]
### Handler should do the following
- process command received from socket
  - call demarshal functions to parse and get operation struct
- use switch statement to determine GET or SET
  - call gwkv_set/get from wrapper
- then do the sending once all data is acquired and set up

**Comment by amygara** [comment]
@nks5295 Same issue, finishing up things. Be sure to keep in contact with the server people. Also, finish your PR and add in the required functions we talked about:
- KV struct init (can be done in main)
- Your logic integrated with server and server-run
- Adjust Makefile to allow for ht_wrapper to be linked in

**Comment by amygara** [comment]
@nks5295 Should be good to go once you address the comments on PR #49 c:

**Comment by amygara** [comment]
Finished and merged into master, see PR #49
