### ISSUE TITLE
Marshalling/Demarshalling APIs

### ISSUE THREAD

**Issue by pradeep-k** [gwAdvNet2015/gw-kv-store#37]
@huyang1988 @Grace-Liu @akorzan 
We need to finish the Marshalling/Demarshalling stuff.
Here is the summary that we did:
1st and 4th API: Done by Yang.
2nd API done by Pradeep
3rd API is being developed by Anthony
We need to finish this as per plan.

Division of the work:
Grace: Please make the code compilable. You can see there is a Makefile and main.c inside lib directory speicifically designed for marshalling/demarshalling. Write a small test function in main.c so that we are able to call any of the APIs for testing. You don't have to write in-depth testing framework except making it run. Then, write one testcases for each of 4 APIs at least. You can write more.

Yang, pradeep and Anthony will then test their apis writing more testing code in main.c or a new file mimicing your written code as per their wish.

I will be merging the repository to main repository by end of day today so that you can fork the main repository.

**Comment by Grace-Liu** [comment]
Thanks Pradeep, the plan sounds good to me.

**Comment by phil-lopreiato** [comment]
For reference, see the test code in `lib/linkedlist/test`, `lib/hashtable/test` and `server/test`

This will show you how you can write tests that travis will run and what kind of output format to use.

**Comment by Grace-Liu** [comment]
@huyang1988 Are you done with 1st and 4th API? It seems your code is not complete such as this valuable hasn't been defined yet. 
https://github.com/gwAdvNet2015/gw-kv-store/blob/client-dev/lib/marshal/marshal.c#L43
Please let me know if this is not your final version, thanks.

**Comment by huyang1988** [comment]
@Grace-Liu Yes I think so. Actually we finished this in class. But we did not tested it together with other parts. Do we have a test plan?

**Comment by Grace-Liu** [comment]
I have wrote a simple test cast for gwkv_marshal_client()
https://github.com/Grace-Liu/gw-kv-store/blob/client-dev/lib/marshal/test/test-marshal.c
@pradeep-k gwkv_marshal_client() currently only converts the first two characters for set case (I think it is because of snprintf) and has segmentation fault for get case, please check. And please take a look at whether my set_cmd and get_cmd strings are right. Thanks.
@huyang1988 please try to finish your code since I am not sure how to handle your undefined variables and try to add status string conversion.

**Comment by pradeep-k** [comment]
The code looks good. Thanks for the testing framework. I will start to debug to fix it.

**Comment by pradeep-k** [comment]
@Grace-Liu 
I fixed the bug. I changed the testfile also little bit based on my understanding. If you find problem with this represention, then let me know.
fixed code can be found in here:
https://github.com/pradeep-k/gw-kv-store/tree/master/lib/marshal
changed files are marshal.c and test-marshal.c

**Comment by Grace-Liu** [comment]
@pradeep-k I've checked the bug has been fixed, thanks.
@huyang1988 there is a bug for SET operation in gwkv_marshal_client, and there is still a undefined variable in gwkv_demarshar_client function, please check. https://github.com/Grace-Liu/gw-kv-store/blob/client-dev/lib/marshal/marshal.c#L163

**Comment by pradeep-k** [comment]
@akorzan @huyang1988 : What stage are you guys in? Let me or Grace know if you need any help. 
We need to have a stable code before we go to class.

**Comment by twood02** [comment]
@pradeep-k @Grace-Liu @huyang1988 @akorzan -- please update this Issue or close it and create a new one listing exactly what is remaining and who will do what

**Comment by pradeep-k** [comment]
Issue #51 has been created. Closing this.
