### ISSUE TITLE
Marshalling/Demarshalling Issues

### ISSUE THREAD

**Issue by pradeep-k** [gwAdvNet2015/gw-kv-store#51]
@akorzan has to complete this gwkv_demarshal_server
@huyang1988 has to fix the bug in gwkv_marshal_server. I believe gwkv_demarshal_client is done. If not flag it asap.
@pradeep-k has finished gwkv_marshal_client. 
@Grace-Liu has finished writing the testcase. If you haven't created the pull request, please do this asap.

Since, other teams are depending on these APIs, we need to make this up first. I am targeting it to be finished by Wednesday 11:59 PM. 
@akorzan and @huyang1988 : Let us know if you guys need any help in finishing this by that time.

**Comment by Grace-Liu** [comment]
@pradeep-k I've created a pull request for the test file.

**Comment by pradeep-k** [comment]
Everything is up now (testcases running) and has been submitted to my repository (branch-name = server-marshal-update).
I am figuring out how to submit this to main repository, server-dev/client-dev branches as pull-request is not showing any difference but manual inspection shows. 

@huyang1988 @Grace-Liu @akorzan : You don't have to do anything. If you see any bugs, u can fix this or raise a new issue and assign me/fix yourself.
