### ISSUE TITLE
Handle key not found with END

### ISSUE THREAD

**Issue by thelimeburner** [gwAdvNet2015/gw-kv-store#60]
When a key is not found, the server should only return END.

**Comment by atryus** [comment]
Fixed, see PR #55

**Comment by amygara** [comment]
Wrongly closed.
@zhangwei1984 @wenhuizhang are fixing the issue.

**Comment by wenhuizhang** [comment]
It is updated, and could return "END" now, thanks, pls close the issue

**Comment by phil-lopreiato** [comment]
Fixed in 312de3a
